layout_spectrum: 0.2490895
typography_spectrum: 0.6537988
color:
  saturation: 0.9447374
  lightness: 0.8883438
  brandStrength: 0.5088248
  rhythmicContrast: 0.7502412
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
name: TusharWadhwa
